# Generated by Django 2.1.7 on 2019-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikeshare',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
