# Generated by Django 2.1.7 on 2019-05-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_notification_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='location',
        ),
    ]
