# Generated by Django 2.1.7 on 2019-04-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_user_location_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikeshare',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
