# Generated by Django 2.1.7 on 2019-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_locations_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='keyWords',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='priceMax',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='priceMin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='totalCheckin',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='totalFavourite',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='totalReview',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='totalView',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='workTime24h',
            field=models.CharField(default='', max_length=255),
        ),
    ]
