# Generated by Django 2.1.7 on 2019-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190325_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='displayOrder',
            field=models.IntegerField(default=0),
        ),
    ]
