# Generated by Django 2.1.7 on 2019-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_requirefromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='created_by',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
