# Generated by Django 2.1.7 on 2019-04-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_locations_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='created_by',
        ),
        migrations.AddField(
            model_name='requirefromuser',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.Locations'),
        ),
    ]
