# Generated by Django 2.1.7 on 2019-05-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20190423_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='created_by',
            field=models.IntegerField(default='1'),
        ),
    ]
