# Generated by Django 2.1.7 on 2019-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_locations_news_tsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='avatar',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
