# Generated by Django 2.1.7 on 2019-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_auto_20190402_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='avatar',
            field=models.CharField(max_length=255),
        ),
    ]
