# Generated by Django 2.1.7 on 2019-05-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_notification_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.Locations'),
        ),
    ]
