# Generated by Django 2.1.7 on 2019-04-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_auto_20190405_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location/')),
            ],
        ),
    ]
