# Generated by Django 2.1.7 on 2019-04-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='keyWords',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='priceMax',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='priceMin',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='workTime24h',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
