# Generated by Django 2.1.7 on 2019-05-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_notification_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='location/'),
        ),
    ]
