# Generated by Django 2.1.7 on 2019-05-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0013_auto_20190510_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadMapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ImageField(blank=True, upload_to='location/')),
            ],
        ),
    ]
