# Generated by Django 2.1.7 on 2019-04-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0013_auto_20190406_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='timeEnd24h',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='locations',
            name='timeStart24h',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
