# Generated by Django 2.1.7 on 2019-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_uploadmapimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadDishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ImageField(upload_to='location/')),
            ],
        ),
    ]
