# Generated by Django 2.1.7 on 2019-04-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0014_auto_20190406_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='timeEnd24h',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='locations',
            name='timeStart24h',
            field=models.CharField(default='00:00 - 00:00', max_length=20),
        ),
    ]
