# Generated by Django 2.1.7 on 2019-04-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0015_auto_20190406_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='timeEnd24h',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='timeStart24h',
        ),
    ]
