# Generated by Django 2.1.7 on 2019-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0016_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.CharField(default='https://www.foody.vn/style/images/deli-dish-no-image.png', max_length=255),
        ),
    ]
