# Generated by Django 2.1.7 on 2019-04-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0016_auto_20190406_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikeshare',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
