# Generated by Django 2.1.7 on 2019-04-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0017_commentlikeshare_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikeshare',
            name='content',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
