# Generated by Django 2.1.7 on 2019-05-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0017_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(default='https://www.foody.vn/style/images/deli-dish-no-image.png', max_length=500),
        ),
    ]
