# Generated by Django 2.1.7 on 2019-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0019_commentlikeshare_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikeshare',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='locations',
            name='evaluation',
            field=models.CharField(default='[0,0,0,0,0,0]', max_length=255),
        ),
    ]
