# Generated by Django 2.1.7 on 2019-04-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0021_commentlikeshare_evaluation'),
    ]

    operations = [

        migrations.AlterField(
            model_name='commentlikeshare',
            name='evaluation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CollectionLocation',
        ),
        migrations.DeleteModel(
            name='Collections',
        ),
    ]
