# Generated by Django 2.1.7 on 2019-04-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0021_commentlikeshare_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinces',
            name='latitude',
            field=models.FloatField(default=21.033333),
        ),
        migrations.AddField(
            model_name='provinces',
            name='longitude',
            field=models.FloatField(default=105.85),
        ),
    ]
