# Generated by Django 2.1.7 on 2019-04-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0023_auto_20190414_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
