# Generated by Django 2.1.7 on 2019-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0024_auto_20190415_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='location',
            field=models.ManyToManyField(through='admin.CollectionLocation', to='admin.Locations'),
        ),

    ]
