# Generated by Django 2.1.7 on 2019-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='recommend_locs',
            field=models.TextField(default=''),
        ),
    ]
