# Generated by Django 2.1.7 on 2019-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190325_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='avatar',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
