# Generated by Django 2.1.7 on 2019-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_accounts_recommend_locs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='recommend_locs',
            field=models.TextField(null=True),
        ),
    ]
