# Generated by Django 2.1.7 on 2019-05-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190428_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadAvatarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='location/avatar/')),
            ],
        ),
    ]
