# Generated by Django 2.1.7 on 2019-05-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190527_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadavatarimage',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
